import { CollectorAnalytics, CollectorNotification, CollectorTraveler } from '../types/collector'

export const collectorAnalytics: CollectorAnalytics = {
  totalAssigned: 128,
  totalPendingPayments: 42,
  collectedThisMonth: 184500,
  upcomingDues: 18,
  monthlyTarget: 250000,
  collectionCompletion: 74,
  pendingRecovery: 65400,
}

export const collectorNotifications: CollectorNotification[] = [
  {
    id: 'n1',
    title: 'Overdue today',
    message: '3 yatris have crossed their due date and need a polite follow-up.',
    time: '5 min ago',
    tone: 'alert',
  },
  {
    id: 'n2',
    title: 'Payment confirmed',
    message: 'Anjali Deshmukh marked her second installment as received via UPI.',
    time: '18 min ago',
    tone: 'success',
  },
  {
    id: 'n3',
    title: 'New assignment',
    message: '7 new sadhaks were assigned to your collection cluster this morning.',
    time: '1 hour ago',
    tone: 'info',
  },
]

export const collectorTravelers: CollectorTraveler[] = [
  {
    id: 't1',
    bookingId: 'BK-CR-2401',
    fullName: 'Anjali Deshmukh',
    yatraName: 'Shri Kedarnath Darshan Yatra',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=800&auto=format&fit=crop',
    phone: '+91 98765 43210',
    whatsapp: '+91 98765 43210',
    totalAmount: 48000,
    amountPaid: 24000,
    dueAmount: 24000,
    dueDate: '28 May 2026',
    status: 'Partial',
    aadhaarUploaded: true,
    selfieUploaded: true,
    travelerConfirmed: true,
    verificationState: 'approved',
    notes: 'Family booking. Prefers morning calls only.',
    tags: ['VIP', 'Morning follow-up'],
    installments: [
      { id: 'i1', label: 'Advance', amount: 12000, dueDate: '10 Apr 2026', status: 'paid' },
      { id: 'i2', label: 'Second installment', amount: 12000, dueDate: '28 May 2026', status: 'current' },
      { id: 'i3', label: 'Final balance', amount: 24000, dueDate: '22 Jun 2026', status: 'upcoming' },
    ],
    targetPercent: 50,
  },
  {
    id: 't2',
    bookingId: 'BK-CR-2408',
    fullName: 'Rohan Kulkarni',
    yatraName: 'Himalayan Seva Retreat',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=800&auto=format&fit=crop',
    phone: '+91 98234 11223',
    whatsapp: '+91 98234 11223',
    totalAmount: 62000,
    amountPaid: 62000,
    dueAmount: 0,
    dueDate: 'Completed',
    status: 'Paid',
    aadhaarUploaded: true,
    selfieUploaded: true,
    travelerConfirmed: true,
    verificationState: 'approved',
    notes: 'Fully paid and ready for travel docs final check.',
    tags: ['Paid', 'Verified'],
    installments: [
      { id: 'i1', label: 'Deposit', amount: 20000, dueDate: '12 Mar 2026', status: 'paid' },
      { id: 'i2', label: 'Mid installment', amount: 22000, dueDate: '19 Apr 2026', status: 'paid' },
      { id: 'i3', label: 'Final balance', amount: 20000, dueDate: '11 May 2026', status: 'paid' },
    ],
    targetPercent: 100,
  },
  {
    id: 't3',
    bookingId: 'BK-CR-2412',
    fullName: 'Meera Joshi',
    yatraName: 'Badrinath Wellness Yatra',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=800&auto=format&fit=crop',
    phone: '+91 97654 33445',
    whatsapp: '+91 97654 33445',
    totalAmount: 54000,
    amountPaid: 18000,
    dueAmount: 36000,
    dueDate: '31 May 2026',
    status: 'Overdue',
    aadhaarUploaded: true,
    selfieUploaded: false,
    travelerConfirmed: false,
    verificationState: 'warning',
    notes: 'Missing selfie. Call after 6 pm only.',
    tags: ['Overdue', 'Needs selfie'],
    installments: [
      { id: 'i1', label: 'Booking token', amount: 18000, dueDate: '02 Apr 2026', status: 'paid' },
      { id: 'i2', label: 'Second installment', amount: 18000, dueDate: '31 May 2026', status: 'current' },
      { id: 'i3', label: 'Final balance', amount: 18000, dueDate: '20 Jun 2026', status: 'upcoming' },
    ],
    targetPercent: 33,
  },
  {
    id: 't4',
    bookingId: 'BK-CR-2419',
    fullName: 'Sanjay Patil',
    yatraName: 'Dwarka Ocean Darshan',
    photo: 'https://images.unsplash.com/photo-1504593811423-6dd665756598?q=80&w=800&auto=format&fit=crop',
    phone: '+91 99111 22334',
    whatsapp: '+91 99111 22334',
    totalAmount: 39000,
    amountPaid: 18000,
    dueAmount: 21000,
    dueDate: '04 Jun 2026',
    status: 'Pending',
    aadhaarUploaded: false,
    selfieUploaded: true,
    travelerConfirmed: false,
    verificationState: 'pending',
    notes: 'Receipt expected by evening. Needs Aadhaar upload.',
    tags: ['Pending docs', 'Call tomorrow'],
    installments: [
      { id: 'i1', label: 'Advance', amount: 18000, dueDate: '21 Apr 2026', status: 'paid' },
      { id: 'i2', label: 'Second installment', amount: 21000, dueDate: '04 Jun 2026', status: 'current' },
      { id: 'i3', label: 'Balance', amount: 0, dueDate: 'TBD', status: 'upcoming' },
    ],
    targetPercent: 46,
  },
]
