export enum NotificationType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  SEVA_CONFIRMED = 'SEVA_CONFIRMED',
  ANNADAN_CONFIRMED = 'ANNADAN_CONFIRMED',
  DONATION_SUCCESS = 'DONATION_SUCCESS',
  VERIFICATION_APPROVED = 'VERIFICATION_APPROVED',
  VERIFICATION_UPDATED = 'VERIFICATION_UPDATED',
  SYSTEM = 'SYSTEM',
}
